# Insumos de Prodcción - Análisis
# Compras vs Consumos
# K:\Control de Gestion\Compras\InsumosProduccion_ComprasVsConsumos2019.xlsx
# JDE - Almacén\Compras Corrientes\Consultas Corrientes\Consulta Libre de Pedidos/Ordenes



import datetime

fecha1= input("Ingrese FECHA DESDE:  (dd/mm/yyyy)")
fecha2= input("Ingrese FECHA HASTA:  (dd/mm/yyyy)")

print(fecha1)
print(fecha2)

import os
os.chdir("C:\Oracle\instantclient_19_3")
import cx_Oracle
cnn = """tptjde/consulta@(DESCRIPTION=(SOURCE_ROUTE=OFF)
                    (ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))
                    (CONNECT_DATA=(SID=tupass)(SRVR=DEDICATED)))"""

oracle = cx_Oracle.connect(cnn)

sql = """SELECT DISTINCT 
PEDIDOS.PDDCTO AS ORDEN_TIPO, PEDIDOS.PDDOCO AS ORDEN_NRO, 
PEDIDOS.PDITM AS NRO_CORTO, 
MAE.IMAITM AS NRO_3RO, 
MAE.IMLITM AS NRO_ARTICULO, 
PEDIDOS.PDDSC1 AS DESCRIP_1, 
TO_CHAR(TP_JTD(PEDIDOS.PDTRDJ),'DD/MM/YYYY') As FECHA_ORDEN,
TO_CHAR(TP_JTD(PEDIDOS.PDPDDJ),'DD/MM/YYYY') As FECHA_PROMET,
TO_CHAR(TP_JTD(PEDIDOS.PDADDJ),'DD/MM/YYYY') As FECHA_RECEPC,
MAE.IMPRP1 AS CC1, 
MAE.IMPRP2 AS CC2, 
MAE.IMPRP3 AS CC3, 
MAE.IMPRP4 AS CC4, 
PEDIDOS.PDLNTY as LIN_TIPO,
PEDIDOS.PDLNID/1000 as LIN_NRO,
PEDIDOS.PDNXTR as EST_SIG,
PEDIDOS.PDOORN as NRO_ORIGINAL,
MAE.IMUOM1 AS UNIDAD, 
DECODE(MAE.IMUOM3,'1M', ((PEDIDOS.PDUORG/10000)*1000), PEDIDOS.PDUORG/10000) AS CANT_PED, 
PEDIDOS.PDCRCD AS MONEDA, 
ROUND(DECODE(PEDIDOS.PDCRCD, 'PES', (PEDIDOS.PDPRRC/10000), (PEDIDOS.PDFRRC/10000)),2) AS PES_COSTO_UNIT, 
ROUND(DECODE(PEDIDOS.PDCRCD, 'PES',  ((PEDIDOS.PDPRRC/10000)*(PEDIDOS.PDUORG/10000)), ((PEDIDOS.PDFRRC/10000)*(PEDIDOS.PDUORG/10000)) ),2) AS PES_COSTO_TOTAL, 
COTIZA.DOLAR,
ROUND(ROUND(DECODE(PEDIDOS.PDCRCD, 'PES', (PEDIDOS.PDPRRC/10000), (PEDIDOS.PDFRRC/10000)),2) / COTIZA.DOLAR,2) as USV_COSTO_INIT,
ROUND(ROUND(DECODE(PEDIDOS.PDCRCD, 'PES',  ((PEDIDOS.PDPRRC/10000)*(PEDIDOS.PDUORG/10000)), ((PEDIDOS.PDFRRC/10000)*(PEDIDOS.PDUORG/10000)) ),2) / COTIZA.DOLAR,2) as USV_COSTO_TOTAL,
PEDIDOS.PDAN8 as PROV_NRO,        
PROVEEDOR.PROV_NOMBRE as PROV_NOMBRE
FROM 
       PRODDTA.F4311 PEDIDOS 
INNER JOIN PRODDTA.F4101 MAE 
       ON PEDIDOS.PDITM=MAE.IMITM 
LEFT OUTER JOIN 
       (SELECT CXCRCD, CXCRDC, ROUND(AVG(CXCRRD),3) AS DOLAR
         FROM PRODDTA.F0015
         WHERE CXCRDC='USV'and CXAN8=0 and
             (TP_JTD(CXEFT) BETWEEN TO_DATE( """ & fecha1 & """,'DD/MM/YYYY') AND TO_DATE( """ & fecha2 & """,'DD/MM/YYYY'))
         GROUP BY CXCRCD, CXCRDC) COTIZA
         ON PEDIDOS.PDCRCD=COTIZA.CXCRCD
LEFT OUTER JOIN
     (SELECT DISTINCT ABAN8, ABALPH AS PROV_NOMBRE        
      FROM PRODDTA.F0101 PROV        
      ) PROVEEDOR
      ON PEDIDOS.PDAN8 = PROVEEDOR.ABAN8
WHERE 
    (MAE.IMPRP4='IXX') and
    ((PEDIDOS.PDDCTO='OC') OR (PEDIDOS.PDDCTO='OP') OR (PEDIDOS.PDDCTO='OI')) and 
    (TP_JTD(PEDIDOS.PDTRDJ) BETWEEN TO_DATE( """ & fecha1 & """,'DD/MM/YYYY') AND TO_DATE( """ & fecha2 & """,'DD/MM/YYYY'))"""
cur = oracle.cursor()
cur.execute(sql)

printHeader = True

for row in cur:
    print(row)
    
cur.close()
oracle.close()